config/routes.rb
Twitteiro::Application.routes.draw do
  root :to => 'tweets#index'

  post 'apoios/create'
  post 'apoios/update'
  get  'apoios/destroy' , :as => :desapoiar

  post 'retuites/create'
  post 'retuites/update'
  get  'retuites/destroy' , :as => :desretuitar
  get  'tuitar/:id', :as => 'tuitar', :to => "tweets#tuitar"
  get  'habilitar', :as => 'habilitar', :to => "tweets#habilitar"

  resource  :sessions
  resources :tweets
  resources :usuarios

  match 'admin',   :to => 'admin#index'
  match 'sobre',   :to => 'info#sobre'
  match 'faq',     :to => 'info#faq'
  match 'contato', :to => 'info#contato'
  match 'privacidade', :to => 'info#privacidade'
  match 'termos',  :to => 'info#termos'
  match 'finalize_session', :to => 'sessions#finalize'
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base

  def deliver
    sleep 10
    update_attribute(:delivered_at, Time.now)
  end
  
  validates_length_of :tweet, :maximum => 160
  validates_presence_of :tweet
  validates_uniqueness_of :tweet
end

app/controllers/tweets_controller.rb
# -*- encoding:utf-8 -*-
class TweetsController < ApplicationController
  before_filter :authenticate
  respond_to :html, :xml

  def deliver
    Delayed::Job.enqueue RetweetingJob.new params[:id]
    redirect_to root_path, :notice => 'Tudo pronto!'
  end
  
  def index
    params[:page] ||= 1
    @tweets = Tweet.where :user_id => session[:id] 
    @tweet = Tweet.new
    respond_with @tweets, @tweet
  end

  def apoio
    @frequencia = Supportship.find params[:id]
  end

  def tuitar
    @tweet = Tweet.find params[:id]
    client.update @tweet.tweet
    redirect_to root_path, :notice => 'Mensagem tuitada!'
  end

  def retuitar
    client.retweet
  end

  def habilitar
    @tweet = Tweet.find params[:id]
    redirect_to root_path, :notice => 'Mensagem habilitada para os seus apoiadores!'
  end

  def new
    @tweet = Tweet.new
    respond_with @tweet
  end

  def edit
    @tweet = Tweet.find params[:id]
  end

  def create
    @tweet  = Tweet.new params[:tweet]
    @tweet.user_id = session[:id]
    if @tweet.save
      cookies[:_tweet_mensagem] = @tweet.id
      flash[:notice] = 'Mensagem salva!'
    else
      flash[:notice] = 'Erro ao criar mensagem.'
    end
    redirect_to root_path
  end

  def update
    @tweet = Tweet.find params[:id]
    @tweet.user_id = session[:id]
    if @tweet.update_attributes params[:tweet]
      flash[:notice] = 'Mensagem atualizada!'
    end
    redirect_to root_path
  end

  def destroy
    @tweet = Tweet.find params[:id]
    @tweet.destroy
    redirect_to root_path, :notice => 'Mensagem apagada.'
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def pretty_datetime(datetime)
    date = datetime.strftime('%b %e, %Y').downcase
    time = datetime.strftime('%l:%M%p').downcase
    content_tag(:span, date, :class => 'date') + " " + content_tag(:span, time, :class => 'time')
  end
end

app/views/tweets/_form.html.erb
<div id='update'>
<%= form_for(@tweet) do |f| %>
  <div class='field'>
    <%= f.label 'Cadastrar nova mensagem' %><br />
    <%= f.text_area :tweet, :id => 'text' %>
    Faltam <span id='countdown'>140</span> Caracteres
  </div>  
  <div class='actions'>
    <%= f.submit 'Cadastrar' %>
  </div>
<% end %>
</div>

app/views/tweets/edit.html.erb
<% title 'Editando mensagem' %>

<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id='error_explanation'>
      <h2><%= pluralize(@tweet.errors.count, 'erro') %> impediram esse Tweet de ser salvo:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='field'>
    <%= f.label 'Atualizar mensagem' %><br />
    <%= f.text_area :tweet, :id => 'text' %>
    Faltam <span id='countdown'>140</span> Caracteres
  </div>
  
  <div class='actions'>
    <%= f.submit 'Atualizar' %>
  </div>
<% end %>
</div>

<%= link_to 'Voltar', root_path %>

app/views/tweets/index.html.erb
<% title 'Início' %>
<div class='usuario'>
  <h2><%= image_tag session[:profile_image_url], :size => '70x70' %> <%= link_to "#{session[:screen_name]}", "http://twitter.com/#{session[:screen_name]}" %></h2>
  <p><%= auto_link session[:bio] %></p>
  <p class='usuario_stats'>
    <% unless session[:location].blank? %>
      <b><%= session[:location] %></b> | 
    <% end %>
    <%= session[:friends_count] %> Seguindo | <%= session[:followers_count] %> Seguidores
  </p>
</div>
<% if notice %>
  <div id='notice'><%= notice %></div>
<% end %>
  <div id='apoiando'> 
    <h3>Apoiando</h3>
    <% for apoio in Apoio.where(:nome_usuario == session[:screen_name]) %>
      <%= link_to apoio.nome_usuario, "/usuarios/#{apoio.nome_usuario}", :class => 'apoiado'  %> (<%= link_to 'Parar de apoiar', desapoiar_url(:id => apoio.id), :confirm => 'Tem certeza?' %>)<br/>
    <% end %>
  </div>
  <h3>Mensagems cadastradas</h3>
  <div class='mensagens'>
    <table>
      <% for tweet in @tweets %>
        <tr>
          <td><%= auto_link(tweet.tweet, :target => '_blank', :username_url_base => "http://#{request.host_with_port}/users/")%></td>
          <td><%= link_to 'habilitar' %>
          <td><%= link_to 'tuitar' , "tuitar/#{tweet.id}" %>
          <td><%= link_to 'editar', edit_tweet_path(tweet) %></td>
          <td><%= link_to 'excluir', tweet, :confirm => 'Tem certeza? Isso é definitivo.', :method => :delete %></td> 
        </tr>
      <% end %>
    </table>
  </div>
  <br/>
  <br>
  <br>
  <br>
  <%= render 'form' %>

app/views/tweets/new.html.erb
<%= render 'form' %>
<%= link_to 'Voltar', root_path %>