config/routes.rb
Twitteiro::Application.routes.draw do
  root :to => 'tweets#index'

  post 'apoios/create'
  post 'apoios/update'
  get  'apoios/destroy' , :as => :desapoiar

  post 'retuites/create'
  post 'retuites/update'
  get  'retuites/destroy' , :as => :desretuitar
  get  'tuitar/:id', :as => 'tuitar', :to => "tweets#tuitar"
  get  'habilitar', :as => 'habilitar', :to => "tweets#habilitar"

  resource  :sessions
  resources :tweets
  resources :usuarios

  match 'admin',   :to => 'admin#index'
  match 'sobre',   :to => 'info#sobre'
  match 'faq',     :to => 'info#faq'
  match 'contato', :to => 'info#contato'
  match 'privacidade', :to => 'info#privacidade'
  match 'termos',  :to => 'info#termos'
  match 'finalize_session', :to => 'sessions#finalize'
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  respond_to :html, :xml
  before_filter :authenticate

  def show
    @usuario      = client.user params[:id]
    @apoio        = Apoio.where(:nome_apoiador => session[:screen_name], :nome_usuario => @usuario.screen_name).last
    @apoiadores   = Apoio.where(:nome_usuario => @usuario.screen_name)
    @retuite      = Retuite.where(:nome_retuitador => session[:screen_name], :nome_usuario => @usuario.screen_name).last
    @retuitadores = Retuite.where(:nome_usuario => @usuario.screen_name)
    respond_with @usuario
  end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/show.html.erb
<% title 'Perfil de ' + @usuario.screen_name %>  
<div class='usuario'>
  <h2><%= image_tag @usuario.profile_image_url, :size => '70x70' %> <%= link_to "#{@usuario.screen_name}", "http://twitter.com/#{@usuario.screen_name}" %></h2>
  <p><%= auto_link @usuario.description %></p>
  <p class='usuario_stats'>
    <% unless @usuario.location.blank? %>
      <b><%= @usuario.location %></b> | 
    <% end %>
    <%= @usuario.friends_count %> Seguindo | <%= @usuario.followers_count %> Seguidores </p>
</div>
<% if session[:screen_name] != @usuario.screen_name %>
  <div class='chamada'>
    <p> Olá <%= session[:screen_name] %>,</p>
    <p> Participe da nossa campanha! Com o Twitter você pode nos ajudar a divulgar nossas ideias através de mensagens de apoio ou Retweets</p>
  </div>

  <div id='mensagens_de_apoio'>
    <h4>MENSAGENS DE APOIO</h4>
    <% if !@apoio %>
      <p>Autorizo a publicar no meu Twitter (<b>@<%= session[:screen_name] %></b>) conteúdo de apoio e notícias de <%= @usuario.name %> com a seguinte frequência:</p>
      <%= form_tag '/apoios/create' do %>
        <%= collection_select :apoio , :frequencia , [ ['48 Horas',48],['24 Horas',24] , ['12 Horas',12] , ['6 Horas',6] , ['4 Horas',4] ] , :last , :first %>
        <%= text_field_tag :nome_usuario , @usuario.screen_name , :style => 'display:none' %>
        <%= submit_tag 'Autorizar' %>
      <% end %>
    <% else %>
      <p>Você já apoia @<%= @usuario.screen_name %>. <%= link_to 'Clique aqui', desapoiar_url(:id => @apoio.id ), :class => 'botao', :confirm => 'Tem certeza?' %> para parar de apoiar.
        <br>
        <br>
        <% form_tag '/apoios/update' do %>
          <%= text_field_tag :id , @apoio.id , :style => 'display:none' %>
          <p>Mudar frequência:<%= collection_select :apoio , :frequencia , [ ['48 Horas',48],['24 Horas',24] , ['12 Horas',12] , ['6 Horas',6] , ['4 Horas',4] ] , :last , :first %>
            <%= submit_tag 'Salvar' %>
          <% end %>
        <% end %>
  </div>

  <div id='retweets'>
    <h4>RETWEETS</h4>
    <% if !@retuite %>
      <p>Autorizo a utilizar meu Twitter (<b>@<%= session[:screen_name] %></b>) para retuitar as mensagens de <%= @usuario.name %> com a seguinte frequência:</p>
      <%= form_tag '/retuites/create' do %>
        <%= collection_select :retuite , :frequencia , [ ['48 Horas',48],['24 Horas',24] , ['12 Horas',12] , ['6 Horas',6] , ['4 Horas',4] ] , :last , :first %>
        <%= text_field_tag :nome_usuario , @usuario.screen_name , :style => 'display:none' %>
        <%= submit_tag 'Autorizar' %>
      <% end %>
    <% else %>
      <p>Você já retuita @<%= @usuario.screen_name %>. <%= link_to 'Clique aqui', desretuitar_url(:id => @retuite.id ), :class => 'botao', :confirm => 'Tem certeza?' %> para parar de retuitar.
        <br>
        <br>
        <% form_tag '/retuites/update' do %>
          <%= text_field_tag :id , @retuite.id , :style => 'display:none' %>
          <p>Mudar frequência:<%= collection_select :retuite , :frequencia , [ ['48 Horas',48],['24 Horas',24] , ['12 Horas',12] , ['6 Horas',6] , ['4 Horas',4] ] , :last , :first %>
            <%= submit_tag 'Salvar' %>
          <% end %>
        <% end %>
  </div>
<% end %>
  <div id='quem_apoia'>
    <h4>QUEM APOIA</h4>
    <% for apoiador in @apoiadores %>
    <p><%= link_to "@#{apoiador.nome_apoiador}", "/usuarios/#{apoiador.nome_apoiador}" %></p>
    <% end %>
  </div>

  <div id='quem_retuita'>
    <h4>QUEM RETUITA</h4>
    <% for retuitador in @retuitadores %>
    <p><%= link_to "@#{retuitador.nome_retuitador}", "/usuarios/#{retuitador.nome_retuitador}" %> </p>
    <% end %>
  </div>