config/routes.rb
Twitteiro::Application.routes.draw do
  root :to => 'tweets#index'

  post 'apoios/create'
  post 'apoios/update'
  get  'apoios/destroy' , :as => :desapoiar

  post 'retuites/create'
  post 'retuites/update'
  get  'retuites/destroy' , :as => :desretuitar
  get  'tuitar/:id', :as => 'tuitar', :to => "tweets#tuitar"
  get  'habilitar', :as => 'habilitar', :to => "tweets#habilitar"

  resource  :sessions
  resources :tweets
  resources :usuarios

  match 'admin',   :to => 'admin#index'
  match 'sobre',   :to => 'info#sobre'
  match 'faq',     :to => 'info#faq'
  match 'contato', :to => 'info#contato'
  match 'privacidade', :to => 'info#privacidade'
  match 'termos',  :to => 'info#termos'
  match 'finalize_session', :to => 'sessions#finalize'
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
  <title>Twitteiro - <%= yield :title %> </title>
  <%= stylesheet_link_tag 'twitteiro' %>
  <%= javascript_include_tag 'http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js', 'rails', 'http://ajax.microsoft.com/ajax/jquery.validate/1.7/jquery.validate.min.js', 'jquery.form', 'twitteiro' %>
  <%= metatags %>
  <%= csrf_meta_tag %>
  <!--[if IE]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <script type="text/javascript"> 
 
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-1693gh81-1']);
  _gaq.push(['_trackPageview']);
 
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>
</head>
<body>
  <% if signed_in? %>
    <div class='topmenu'>
      Olá, <b><%= link_to "#{session[:screen_name]}", "/usuarios/#{session[:screen_name]}", :class=> 'perfil' %></b>! <%= link_to 'Sair', sessions_url, :method => :delete %>
    </div>
  <% end %>

  <div class='logo'>
    <%= link_to image_tag('logo.png'), root_path %><p>Mobilize seus clientes no Twitter</p>
  </div>

  <%= yield %>

<br>
<br>
<br>
<div class='rodape'>
  <p><%= link_to 'sobre', sobre_path %> <%= link_to 'faq', faq_path %> <%= link_to 'contato', contato_path %> <%= link_to 'privacidade', privacidade_path %> <%= link_to 'termos', termos_path %> </p><p class='copy'> &copy; 2010 Orygens.com. Todos os direitos reservados.</p>
</div>
<br>
<br>
</body>
</html>

app/views/layouts/info.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
  <title>Twitteiro - <%= yield :title %> </title>
  <%= stylesheet_link_tag 'info' %>
  <%= javascript_include_tag 'http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js', 'http://ajax.microsoft.com/ajax/jquery.validate/1.7/jquery.validate.min.js', 'rails', 'jquery.form', 'twitteiro' %>
  <%= metatags %>
  <%= csrf_meta_tag %>
</head>
<body>
  
  <div class='logo'>
    <%= link_to image_tag('logo.png'), root_path %><p>Mobilize seus clientes no Twitter</p>
  </div>

  <%= yield %>

<br>
<br>
<br>

<div class='rodape'>
  <p><%= link_to 'sobre', sobre_path %> <%= link_to 'faq', faq_path %> <%= link_to 'contato', contato_path %> <%= link_to 'privacidade', privacidade_path %> <%= link_to 'termos', termos_path %> </p><p class='copy'> &copy; 2010 Orygens.com. Todos os direitos reservados.</p>
</div>
</body>
</html>